router bgp 65100
 bgp router-id 10.255.0.5
 !
 no bgp ebgp-requires-policy
 !
 no bgp default ipv4-unicast
 !
 neighbor 10.20.0.21 remote-as 65000
 neighbor 10.20.0.21 description L3_TO_R3
 neighbor 10.20.0.25 remote-as 65000
 neighbor 10.20.0.25 description L3_TO_R4
 neighbor 2001:db8:2000:6::1 remote-as 65000
 neighbor 2001:db8:2000:6::1 description L3_TO_R3_V6
 neighbor 2001:db8:2000:7::1 remote-as 65000
 neighbor 2001:db8:2000:7::1 description L3_TO_R4_V6
 !
 address-family ipv4 unicast
  network 10.30.0.0/24
  neighbor 10.20.0.21 activate
  neighbor 10.20.0.25 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:db8:3000:100::/64
  neighbor 2001:db8:2000:6::1 activate
  neighbor 2001:db8:2000:7::1 activate
 exit-address-family
